package com.netease.shop.Mapper;

import com.netease.shop.Entity.Orderinfo;
import com.netease.shop.To.showTo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    int insertSelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    Orderinfo selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orderinfo record);

    List<Orderinfo> selectbyuser(Integer userid);

    List<Integer> selectgoodlistbyuser(Integer userid);

    List<Integer> sellerSelectgoodlist();
    Orderinfo selectByGoodAndUser(showTo to);
}