package com.netease.shop.Mapper;

import com.netease.shop.Entity.Shopcart;
import com.netease.shop.Entity.ShopcartKey;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface ShopcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ShopcartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insert(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int insertSelective(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    Shopcart selectByPrimaryKey(ShopcartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shopcart record);

    int selectCount(Shopcart record);

    List<Shopcart> selectbyuser(Integer id);
}