package com.netease.shop.Entity;

import java.util.Date;

public class Orderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderId
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderTime
     *
     * @mbggenerated
     */
    private Date ordertime;

    private String nowtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.purchasedAmount
     *
     * @mbggenerated
     */
    private Integer purchasedamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.purchasedUnitPrice
     *
     * @mbggenerated
     */
    private Integer purchasedunitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.priceSum
     *
     * @mbggenerated
     */
    private Integer pricesum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.isCompleted
     *
     * @mbggenerated
     */
    private String iscompleted;

    public String getNowtime() {
        return nowtime;
    }

    public void setNowtime(String nowtime) {
        this.nowtime = nowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderId
     *
     * @return the value of orderinfo.orderId
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderId
     *
     * @param orderid the value for orderinfo.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.userId
     *
     * @return the value of orderinfo.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.userId
     *
     * @param userid the value for orderinfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.goodsId
     *
     * @return the value of orderinfo.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.goodsId
     *
     * @param goodsid the value for orderinfo.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderTime
     *
     * @return the value of orderinfo.orderTime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderTime
     *
     * @param ordertime the value for orderinfo.orderTime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.purchasedAmount
     *
     * @return the value of orderinfo.purchasedAmount
     *
     * @mbggenerated
     */
    public Integer getPurchasedamount() {
        return purchasedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.purchasedAmount
     *
     * @param purchasedamount the value for orderinfo.purchasedAmount
     *
     * @mbggenerated
     */
    public void setPurchasedamount(Integer purchasedamount) {
        this.purchasedamount = purchasedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.purchasedUnitPrice
     *
     * @return the value of orderinfo.purchasedUnitPrice
     *
     * @mbggenerated
     */
    public Integer getPurchasedunitprice() {
        return purchasedunitprice;
    }


    public void setPurchasedunitprice(Integer purchasedunitprice) {
        this.purchasedunitprice = purchasedunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.priceSum
     *
     * @return the value of orderinfo.priceSum
     *
     * @mbggenerated
     */
    public Integer getPricesum() {
        return pricesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.priceSum
     *
     * @param pricesum the value for orderinfo.priceSum
     *
     * @mbggenerated
     */
    public void setPricesum(Integer pricesum) {
        this.pricesum = pricesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.isCompleted
     *
     * @return the value of orderinfo.isCompleted
     *
     * @mbggenerated
     */
    public String getIscompleted() {
        return iscompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.isCompleted
     *
     * @param iscompleted the value for orderinfo.isCompleted
     *
     * @mbggenerated
     */
    public void setIscompleted(String iscompleted) {
        this.iscompleted = iscompleted == null ? null : iscompleted.trim();
    }
}