package com.netease.shop.Entity;

public class ShopcartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.user_id
     *
     * @return the value of shopcart.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.user_id
     *
     * @param userId the value for shopcart.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.goods_id
     *
     * @return the value of shopcart.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.goods_id
     *
     * @param goodsId the value for shopcart.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }


    public ShopcartKey() {
    }

    public ShopcartKey(Integer userId, Integer goodsId) {
        this.userId = userId;
        this.goodsId = goodsId;
    }
}