package com.netease.shop.Entity;

public class Shopcart extends ShopcartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcart.purchasedAmount
     *
     * @mbggenerated
     */
    private Integer purchasedamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcart.purchasedAmount
     *
     * @return the value of shopcart.purchasedAmount
     *
     * @mbggenerated
     */
    public Integer getPurchasedamount() {
        return purchasedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcart.purchasedAmount
     *
     * @param purchasedamount the value for shopcart.purchasedAmount
     *
     * @mbggenerated
     */
    public void setPurchasedamount(Integer purchasedamount) {
        this.purchasedamount = purchasedamount;
    }
}